[project]
name = "system-monitor-service-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.5",
    "psutil>=7.0.0",
    "pyqtgraph>=0.13.7",
]
